### ISSUE TITLE
Ubuntu Error.

### ISSUE THREAD

**Issue by shenol** [smtaydemir/freebook#1]
TypeError: Cannot read property 'results' of undefined
    at Request._callback (/usr/local/lib/node_modules/freebook/index.js:9:28)
    at Request.self.callback (/usr/local/lib/node_modules/freebook/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/freebook/node_modules/request/request.js:1036:10)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/freebook/node_modules/request/request.js:963:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by smtaydemir** [comment]
Şuanda apide bir sıkıntı var sanırım, kimono kaynaklı. çözmeye çalışacağım
